// Generated by CoffeeScript 1.6.3
var app, config, port, server;

config = require("./config/config");

port = config.listenPort || 9020;

process.on("uncaughtException", function(err) {
  return console.error("[uncaught-error] exception: " + err + "\r\nstack: " + err.stack);
});

app = require("./config/bootstrap")(__dirname);

server = app.listen(port, function() {
  return console.log("Begin listening on port " + port);
});
