// Generated by CoffeeScript 1.6.3
var Q, getRuleResult, redis, show;

Q = require("q");

redis = require("../common/redisBiz");

module.exports = function(app) {
  app.get("/health-check-result/:ruleId", show);
  return app.param("ruleId", getRuleResult);
};

show = function(req, res) {
  return res.json(req.healthResult);
};

getRuleResult = function(req, res, next, id) {
  var key;
  key = "HealthCheck:" + id;
  return redis.getFromRedis(key).then(function(result) {
    req.healthResult = result;
    return next();
  }, function(error) {
    return next("Fail to get health rule: " + id);
  });
};
