// Generated by CoffeeScript 1.6.3
var config, cors, express, fileMonitor, fs, healthCheck;

fs = require("fs");

express = require('express');

cors = require('cors');

config = require("./config");

healthCheck = require("../check/checkEntry").healthCheck;

fileMonitor = require("file-monitor");

module.exports = function(appPath) {
  var app, domainError, healthRule, options, routes_path;
  domainError = require("../common/domainError");
  app = express();
  app.configure(function() {
    app.use(express.urlencoded({
      limit: '10mb'
    }));
    app.use(express.json({
      limit: '10mb'
    }));
    app.use(express.methodOverride());
    app.use(cors());
    app.use(domainError());
    app.use(app.router);
    return app.use(function(err, req, res, next) {
      res.statusCode = 500;
      res.json({
        Message: err.message,
        Stack: err.stack
      });
      return res.end();
    });
  });
  routes_path = appPath + "/routes";
  fs.readdirSync(routes_path).forEach(function(file) {
    var newPath, stat;
    newPath = routes_path + "/" + file;
    stat = fs.statSync(newPath);
    if (stat.isFile()) {
      if (/(.*)\.(js$)/.test(file)) {
        return require(newPath)(app);
      }
    }
  });
  healthRule = fs.readFileSync(appPath + "/config/health-check-rules.json");
  healthCheck.run(JSON.parse(healthRule));
  options = {
    tryParseJson: true,
    filter: function(file, stat) {
      if (file.indexOf("health-check-rules.json") > -1) {
        return true;
      } else {
        return false;
      }
    }
  };
  fileMonitor.watchDirectory(appPath + "/config", options, function(err, f, c, p, data) {
    if (err == null) {
      return healthCheck.run(data);
    }
  });
  return app;
};
