// Generated by CoffeeScript 1.6.3
var config, cors, express, fs;

fs = require("fs");

express = require('express');

cors = require('cors');

config = require("../config/config");

module.exports = function(appPath) {
  var app, domainError, routes_path;
  domainError = require("../common/domainError");
  app = express();
  app.configure(function() {
    app.use(express.urlencoded({
      limit: '10mb'
    }));
    app.use(express.json({
      limit: '10mb'
    }));
    app.use(express.methodOverride());
    app.use(cors());
    app.use(domainError());
    app.use(app.router);
    return app.use(function(err, req, res, next) {
      res.statusCode = 500;
      res.json({
        Message: err.message,
        Stack: config.debug === true ? err.stack : void 0
      });
      return res.end();
    });
  });
  routes_path = appPath + "/routes";
  fs.readdirSync(routes_path).forEach(function(file) {
    var newPath, stat;
    newPath = routes_path + "/" + file;
    stat = fs.statSync(newPath);
    if (stat.isFile()) {
      if (/(.*)\.(js$)/.test(file)) {
        return require(newPath)(app);
      }
    }
  });
  return app;
};
