// Generated by CoffeeScript 1.6.3
var CheckResultStore, resultStore;

CheckResultStore = (function() {
  CheckResultStore.prototype.setSaveAdapter = function(storeAdapter) {
    return this.sad = storeAdapter;
  };

  function CheckResultStore() {
    this.data = {};
    this.sad = null;
  }

  CheckResultStore.prototype.set = function(key, value) {
    this.data[key] = value;
    return this.save();
  };

  CheckResultStore.prototype.get = function(key) {
    var _ref;
    return (_ref = this.data[key]) != null ? _ref : null;
  };

  CheckResultStore.prototype.remove = function(key) {
    if (this.data[key] != null) {
      return delete this.data[key];
    }
  };

  CheckResultStore.prototype.save = function() {
    if (this.sad != null) {
      return this.sad(this.data);
    }
  };

  return CheckResultStore;

})();

resultStore = new CheckResultStore();

exports.ResultStore = resultStore;
