// Generated by CoffeeScript 1.6.3
var domain;

domain = require("domain");

module.exports = function() {
  return function(req, res, next) {
    var d;
    d = domain.create();
    d.add(req);
    d.add(res);
    d.on("error", function(err) {
      d._throwErrorCount = (d._throwErrorCount || 0) + 1;
      if (d._throwErrorCount > 1) {
        console.error("[domain-error] " + req.method + " " + req.url + " throw error " + d._throwErrorCount + " times");
        console.error(err);
        return;
      }
      res.setHeader("Connection", "close");
      return next(err);
    });
    return d.run(next);
  };
};
