// Generated by CoffeeScript 1.6.3
var Q, client, config, logger, redis;

redis = require("redis");

logger = require("./logger");

config = require("../config/config");

Q = require("q");

client = redis.createClient(6379, config.redisHost);

client.on("error", function(err) {
  return logger.error("Redis Error " + err);
});

client.select(config.redisDB);

exports.getFromRedis = function(key) {
  var deferred;
  deferred = Q.defer();
  client.get(key, function(err, value) {
    var obj;
    if (err != null) {
      deferred.reject(err);
      return logger.error("Redis Get Error: " + err + ". key: " + key);
    } else if (value != null) {
      try {
        obj = JSON.parse(value);
        return deferred.resolve(obj);
      } catch (_error) {
        return deferred.resolve(value);
      }
    } else {
      return deferred.resolve(null);
    }
  });
  return deferred.promise;
};

exports.setToRedis = function(key, value) {
  var deferred;
  deferred = Q.defer();
  client.set(key, value, function(err, reply) {
    if (err != null) {
      deferred.reject(err);
      return logger.error("Redis Set Error: " + err + ". key: " + key);
    } else {
      return deferred.resolve(null);
    }
  });
  return deferred.promise;
};
