// Generated by CoffeeScript 1.7.1
(function() {
  var crypto;

  crypto = require("crypto");

  exports.getHash = function(data) {
    return crypto.createHash("md5").update(data).digest("hex");
  };

}).call(this);

//# sourceMappingURL=util.map
