// Generated by CoffeeScript 1.6.3
var request;

request = require('request');

exports.checkHealth = function(rule, callback) {
  var options;
  options = {
    url: rule.Url,
    timeout: 10 * 1000
  };
  return request(options, function(err, response, body) {
    if (err != null) {
      return callback(false);
    } else if (response.statusCode >= 400) {
      return callback(false);
    } else if (rule.EnableStringMatching) {
      return callback(body === rule.MatchString);
    } else {
      return callback(true);
    }
  });
};
