// Generated by CoffeeScript 1.7.1
(function() {
  var request;

  request = require('request');

  exports.checkHealth = function(rule, callback) {
    var options;
    options = {
      url: rule.Url,
      timeout: 10 * 1000
    };
    return request(options, function(err, response, body) {
      var actualHash, ruleHash;
      if (err != null) {
        return callback(false);
      } else if (response.statusCode >= 400) {
        return callback(false);
      } else if (rule.EnableStringMatching) {
        var actualHash, ruleHash;
        ruleHash = rule.MatchString.replace(/\r?\n|\r/g, "");
        actualHash = body.replace(/\r?\n|\r/g, "");
        return callback(ruleHash === actualHash);
      } else {
        return callback(true);
      }
    });
  };

}).call(this);

//# sourceMappingURL=http.map
