// Generated by CoffeeScript 1.6.3
var net;

net = require("net");

exports.checkHealth = function(rule, callback) {
  var returned, socket;
  socket = new net.Socket();
  returned = false;
  socket.setTimeout(10 * 1000, function() {
    returned = true;
    socket.end();
    return callback(false);
  });
  socket.connect(rule.Port, rule.Host, function() {
    if (!returned) {
      returned = true;
      callback(true);
    }
    return socket.end();
  });
  return socket.on("error", function(err) {
    socket.destroy();
    if (!returned) {
      returned = true;
      return callback(false);
    }
  });
};
